### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by woshichenghaibo** [svoop/wowmow#1]
help me please.
I have a local host  192.168.1.11:9000
I bind it to my domain name http://a.name.com:9000
so:
how can I modify your repo now?

**Comment by svoop** [comment]
I honestly don't understand what you mean. You can bind your local 192.168.1.11:9000 to a web service on render.com which serves https://whatever.com. But you can't expose port 9000 using a web service on render.com.

In any case, the README is too complicated, I'll simplify it these days.

**Comment by svoop** [comment]
I've reworked the README as of 48fefc722f976c3454e7c7f644bae0bdfb870aa3, hopefully the install and usage instructions are now less confusing.
